baseurl = "https://romain.rbind.io/"
title = "Romain François - Consulting Datactive"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "romain-rbind-io"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

# Define the number of posts per page
paginate = 10

[menu]

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[params]
    viewMorePostLink = "/blog/"
    author = "Romain François"
    defaultKeywords = ["r"]
    defaultDescription = "Romain François. Consulting Datactive"
    githubContentURL = "https://github.com/rbind/romain/edit/master/content/"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "romain@thinkr.fr"

    about_us = """<p>I am <a href='www.thinkr.fr'>ThinkR</a>'s consulting
      datactive since february 2017. Passionated about anything related to R.
      I take performance seriously, hence my historical involvment with the
      design and implementation of
      <a href="https://github.com/RcppCore/Rcpp">Rcpp</a>. I have written
      the C++ internals of <a href="https://github.com/tidyverse/dplyr">dplyr</a></p>
      """
    copyright = "Copyright (c) 2017, Romain Francois; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "2006/01/02"

    logo = "img/logo.png"
    address = """
        <strong>Romain François</strong><br/>
        6 Impasse Joseph Vidal<br/>
        34000 Montpellier<br/>
        FRANCE
      """
    latitude = "43.604057"
    longitude = "3.86920"

[Permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

[params.social]
    twitter = "romain_francois"
    github = "romainfrancois"
    linkedin = "romain-francois"
    stackoverflow = "499163/romain-francois"
    researchgate = "Romain_Francois2"
    email = "romain@thinkr.fr"
    mobile = "+33(0) 6 28 91 30 30"
    youtube = "UCd357E9PIj497TXmYRtKliw"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From my blog"
    subtitle = "I mostly blog about things that are at least remotely related to R in some way. "
